-- Execute este arquivo uma única vez no SQL Editor do Supabase.
create extension if not exists pgcrypto;

create table if not exists public.pedidos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  usuario_id uuid references auth.users(id) on delete set null,
  status_pedido text not null default 'novo'
    check (status_pedido in ('novo', 'em_separacao', 'enviado', 'entregue', 'cancelado')),
  status_pagamento text not null default 'aguardando'
    check (status_pagamento in ('aguardando', 'em_analise', 'aprovado', 'recusado', 'cancelado', 'estornado', 'erro')),
  mercado_pago_preferencia_id text,
  mercado_pago_pagamento_id text unique,
  cliente_nome text not null,
  cliente_email text not null,
  cliente_telefone text,
  endereco_cep text not null,
  endereco_rua text not null,
  endereco_numero text not null,
  endereco_complemento text,
  endereco_bairro text not null,
  endereco_cidade text not null,
  endereco_estado text not null,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  frete numeric(12,2) not null default 0 check (frete >= 0),
  total numeric(12,2) not null check (total >= 0),
  moeda text not null default 'BRL',
  pago_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.pedido_itens (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  -- Texto para funcionar tanto com IDs numéricos quanto UUID no catálogo atual.
  produto_id text,
  nome text not null,
  imagem_url text,
  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(12,2) not null check (preco_unitario >= 0),
  total numeric(12,2) not null check (total >= 0),
  criado_em timestamptz not null default now()
);

create index if not exists pedidos_usuario_id_idx on public.pedidos(usuario_id);
create index if not exists pedidos_criado_em_idx on public.pedidos(criado_em desc);
create index if not exists pedidos_status_pagamento_idx on public.pedidos(status_pagamento);
create index if not exists pedido_itens_pedido_id_idx on public.pedido_itens(pedido_id);

alter table public.pedidos enable row level security;
alter table public.pedido_itens enable row level security;

drop policy if exists "Cliente visualiza os proprios pedidos" on public.pedidos;
create policy "Cliente visualiza os proprios pedidos"
on public.pedidos for select
to authenticated
using (auth.uid() = usuario_id);

drop policy if exists "Cliente visualiza os itens dos proprios pedidos" on public.pedido_itens;
create policy "Cliente visualiza os itens dos proprios pedidos"
on public.pedido_itens for select
to authenticated
using (
  exists (
    select 1 from public.pedidos
    where pedidos.id = pedido_itens.pedido_id
      and pedidos.usuario_id = auth.uid()
  )
);

-- Confirma o pagamento e baixa o estoque uma única vez, mesmo que o webhook seja repetido.
create or replace function public.confirmar_pagamento_virella(
  p_pedido_id uuid,
  p_pagamento_id text,
  p_pago_em timestamptz
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  status_atual text;
begin
  select status_pagamento into status_atual
  from public.pedidos
  where id = p_pedido_id
  for update;

  if status_atual is null then
    raise exception 'Pedido não encontrado';
  end if;

  if status_atual <> 'aprovado' then
    update public.pedidos
    set status_pagamento = 'aprovado',
        mercado_pago_pagamento_id = p_pagamento_id,
        pago_em = coalesce(p_pago_em, now()),
        atualizado_em = now()
    where id = p_pedido_id;

    update public.produtos as produto
    set quantidade = greatest(0, coalesce(produto.quantidade, 0) - item.quantidade)
    from public.pedido_itens as item
    where item.pedido_id = p_pedido_id
      and produto.id::text = item.produto_id;
  end if;
end;
$$;

revoke all on function public.confirmar_pagamento_virella(uuid, text, timestamptz) from public;
grant execute on function public.confirmar_pagamento_virella(uuid, text, timestamptz) to service_role;
